# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tenetx < Formula
  desc "Secure your AI coding agents — the TenetX CLI"
  homepage "https://tenetx.ai"
  version "0.4.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TenetxAI/homebrew-tap/releases/download/v0.4.10/tenetx_darwin_amd64.tar.gz"
      sha256 "d2ba79ada5139019c2a59a88f0baff63a4ab73e6b085016d25f6dcdf454f9eae"

      define_method(:install) do
        bin.install "tenetx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TenetxAI/homebrew-tap/releases/download/v0.4.10/tenetx_darwin_arm64.tar.gz"
      sha256 "62b9adc9dd6b671713f43a94d675c5b545751bac59a025430a3826dbb590192b"

      define_method(:install) do
        bin.install "tenetx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TenetxAI/homebrew-tap/releases/download/v0.4.10/tenetx_linux_amd64.tar.gz"
      sha256 "eef640d83a6d897c4993f81fc30533eb8ae6d4d83e051bdcabedd11c080624ac"
      define_method(:install) do
        bin.install "tenetx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TenetxAI/homebrew-tap/releases/download/v0.4.10/tenetx_linux_arm64.tar.gz"
      sha256 "809443b8163f98251e5ce6ffa74cbc99c8cb9fabe5c0ec7b48b58d9b23bb2ca2"
      define_method(:install) do
        bin.install "tenetx"
      end
    end
  end

  test do
    system "#{bin}/tenetx", "version"
  end
end
