# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tenetx < Formula
  desc "Secure your AI coding agents — the TenetX CLI"
  homepage "https://tenetx.ai"
  version "0.4.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TenetxAI/homebrew-tap/releases/download/v0.4.8/tenetx_darwin_amd64.tar.gz"
      sha256 "d716f91a4078c484a5e66d095a42924c65f576712dd8f9596fefbdf25e8d79f7"

      define_method(:install) do
        bin.install "tenetx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TenetxAI/homebrew-tap/releases/download/v0.4.8/tenetx_darwin_arm64.tar.gz"
      sha256 "89c60ab65a29d515d142e3cccbfd570bfa2a15bad901a391f3153d333555e7e3"

      define_method(:install) do
        bin.install "tenetx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TenetxAI/homebrew-tap/releases/download/v0.4.8/tenetx_linux_amd64.tar.gz"
      sha256 "dd9df12d8a89b304439952a7aba34df31c26906ab5a9a5507e346bd396705f62"
      define_method(:install) do
        bin.install "tenetx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TenetxAI/homebrew-tap/releases/download/v0.4.8/tenetx_linux_arm64.tar.gz"
      sha256 "5e0f238e39e169012a589df697bfd6094e43851db616e1e440e1dd8fd02d39f0"
      define_method(:install) do
        bin.install "tenetx"
      end
    end
  end

  test do
    system "#{bin}/tenetx", "version"
  end
end
